server:
  port: 7001

spring:
  application:
    ## 应用程序名称
    name: springcloud-swagger

eureka:
  client:
    serviceUrl:
      ## 需要将我的服务注册到eureka上面，这里就是eureka的地址
      defaultZone: http://localhost:3000/eureka
    ## 需要将我们的服务注册到eureka上面，默认为true
    register-with-eureka: true
    ## 需要检索服务，默认为true
    fetch-registry: true
