server:
  port: 4002

spring:
  application:
    ## 应用程序名称，后面会在消费者中用到  使用ribbon实现负载均衡的时候，服务名称不能用下划线，换成中划线。
    name: springcloud-framework-order

eureka:
  instance:
    preferIpAddress: true

    # 心跳检测与续约时间
    # 测试的时候将值设置的小些，保证服务关闭后注册中心能及时提出服务
    ### Eureka客户端想服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 1
    ### Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除 （客户端会告诉服务端按照此规则）
    lease-expiration-duration-in-seconds: 2

  client:
    serviceUrl:
      ## 需要将我的服务注册到eureka上面，这里就是eureka的地址
      defaultZone: http://localhost:3000/eureka
    ## 需要将我们的服务注册到eureka上面，默认为true
    register-with-eureka: true
    ## 需要检索服务，默认为true
    fetch-registry: true

# Springcloud feign 默认开启支持ribbon
ribbon:
  ## 指定建立连接所用的时间，适用于网络状态正常的情况下，两端连接所用的时间，单位ms
  ReadTimeout: 5000
  ## 指定建立连接后从服务器读取到可用资源所用的时间，单位ms， 默认为1s
  ConnectionTimeout: 5000

